disabled: true
python_module: eduid_dashboard_amp
python_source_directory: eduid_dashboard_amp
publish_over_ssh:
  - pypi.sunet.se
upstream:
  - eduid-userdb
slack:
  room: eduid-builds
clean_workspace: true
